22-10-2020 13:02:17 INFO - Starting webdriver initialization
22-10-2020 13:02:21 INFO - Webdriver initializated
22-10-2020 13:02:26 INFO - Starting Google authorization
22-10-2020 13:02:30 INFO - Get to google authorization page
22-10-2020 13:02:31 ERROR - Exception on /googlelogin [POST]
Traceback (most recent call last):
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/app.py", line 104, in googlelogin
    if core.send_mail():
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/core.py", line 50, in send_mail
    driver.find_element_by_name('Email').send_keys(MAIL)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/spaceshinobi/PycharmProjects/GoogleMeetSelenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="Email"]"}
  (Session info: headless chrome=86.0.4240.111)

